apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-app-dep-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: books-app-dep-canary
  template:
    metadata:
      labels:
        app: books-app-dep-canary
    spec:
      containers:
      - name: books-app-v1-canary
        image: monyslim/books-app:12700
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: books-app-serv-canary
spec:
  type: LoadBalancer
  selector:
    app: books-app-dep
  ports:
  - port: 8081
    targetPort: 80

