apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-app-dep-canary
spec:
  replicas: 3
  selector:
    matchLabels:
      app: books-app-dep-canary
  template:
    metadata:
      labels:
        app: books-app-dep-canary
    spec:
      containers:
      - name: books-app-v1
        image: monyslim/books-app:21603
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: books-app-serv-canary
spec:
  type: LoadBalancer
  selector:
    app: books-app-dep-canary
  ports:
  - port: 8081
    targetPort: 80

