name: "Deployment Workflow"
on:
    push:
        branches:
            - master
jobs:
    simple_deploy:
        runs-on: ubuntu-latest
        steps:
        - name: "Checkout repo"
          uses: actions/checkout@v2

        - name: "Build the image"
          run: |
            docker build -t monyslim/books-app:1.1 .

        - name: "Login to DockerHub"
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
        - name: "Push image to DockerHub"
          run: |
            docker push monyslim/books-app:1

            